Part 11: Аутентификация с Devise. Rails Mailer. STI
Kagayakashi/learn_rails pull request #11
Opened 2021-04-01 16:14 UTC by Kagayakashi

1. Реализуйте аутентификацию в проекте при помощи библиотеки Devise
2. Сделайте управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализуйте перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратором назначайте его в качестве автора теста

Усложненное задание:

При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить флэш-сообщение "Привет, <имя пользователя>!"

2021-04-02 05:45 UTC, VidgarVii requested changes

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
> +    end
у тебя сейчас длинные ссылки и происходят лишние запросы в БД.
Используй опцию shallow: true

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
> +  devise_for :admins, path: 'admins'
это лишние

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
>    resources :categories
1 разве была задача создавать маршруты для категорий?
2 зачем обычному юзеру полноценные CRUD операции?

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
> +  resources :tests, only: :start do
а вот список тестов как раз стоило бы вывести
я подразумеваю тут у тебя ошибка

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
> +      end
не все маршруты тут используются. Надо убрать лишние

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
> +  end
эти сложности тут не нужны

2021-04-02 05:45 UTC, VidgarVii commented on config/routes.rb
> +
3 роута выше под удаление

2021-04-02 05:45 UTC, VidgarVii commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = {host: '217.24.65.184', port: 80}
{ host: 'localhost', port: 3000 }

2021-04-02 05:45 UTC, VidgarVii commented on app/views/categories/show.html.erb
> +</div>
отступы должны быть в 2 пробела

2021-04-02 05:45 UTC, VidgarVii commented on app/controllers/users/registrations_controller.rb
> +
вот корректное решение
https://www.rubydoc.info/github/plataformatec/devise/Devise/ParameterSanitizer

2021-04-02 05:45 UTC, VidgarVii commented on app/controllers/users/unlocks_controller.rb
> +end
все эти контроллеры девайса с комментами под удаление. Только загрязняют код

2021-04-02 05:45 UTC, VidgarVii commented on app/views/admin/answers/_answer.html.erb
> +	<%= link_to 'Удалить', admin_test_question_answer_path(answer.question.test, answer.question, answer),
километровые не читабельные ссылки лечатся опцией shallow в роутах

2021-04-02 05:45 UTC, VidgarVii commented on app/controllers/registrations_controller.rb
> +end
последние 2 методы не будут использоваться. Получается в наследовании нет смысла. Ниже ссылка как передовать параметры из формы

2021-04-02 05:45 UTC, VidgarVii commented on app/controllers/application_controller.rb
>  end
отступы!

2021-04-02 05:45 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
>      @test.creator = current_user
http://rusrails.ru/active-record-associations#build_association-attributes
это сократит код

2021-04-02 14:07 UTC, Kagayakashi commented on config/routes.rb
> +  resources :tests, only: :start do
Я решил, что список тестов у меня будет в выбранной категории.
То есть category#show/:id

Пользователь выбирает категорию и видит список тестов для неё, может вернется назад и сменить категорию.

Делать общий список тестов не стал делать, получиться каша без фильтрации :)

2021-04-06 10:16 UTC, VidgarVii commented on app/controllers/registrations_controller.rb
>    end
не надо полностью переопределять методы devise
Есть готовое решение https://www.rubydoc.info/github/plataformatec/devise/Devise/ParameterSanitizer

2021-04-06 10:16 UTC, VidgarVii commented on app/helpers/answers_helper.rb
>      end
```
text = 
  if answer.persisted?
    ...
  else
```

2021-04-06 10:16 UTC, VidgarVii commented on app/models/user.rb
>    validates :email, format: { with: /(.+)@(.+)/ },
валидацию `:email` уже можно убрать - за тебя валидации `Devise` делает (опция `:validatable`)

2021-04-06 10:16 UTC, VidgarVii commented on app/views/admin/answers/_form.html.erb
> +<%= answer_header answer: @answer, question: @question || @answer.question %>
достаточно одного ответа. А сейчас можно по гадать. а вопрос точно тот который связан с ответом?

2021-04-06 12:06 UTC, Kagayakashi commented
Завершено

2021-04-06 12:06 UTC, merged