Добавление Наград
Kagayakashi/learn_rails pull request #23
Opened 2021-11-15 22:26 UTC by Kagayakashi

Разработайте функционал который позволит пользователям получать бэйджи (награды) за успешное прохождение тестов.

Бэйджи представляются моделью Badge
Пользователь может получать один и тот же бэйдж более одного раза
Бэйдж обязательно содержит атрибуты:
    Название
    Имя файла с изображением (Делать загрузку изображений не нужно. Это может быть статический файл с изображением который вручную добавляется в проект. Либо это может быть любой URL с изображением бэйджа)
Выдача бэйджов происходит автоматически после завершения теста
Управление бэйджами осуществляется администратором
При создании бэйджа администратор также назначает правило которое определяет порядок выдачи бэйджа. Примеры правил:
    Выдать бэйдж после успешного прохождения всех тестов из категории Backend
    Выдать бэйдж после успешного прохождения теста с первой попытки
    Выдать бэйдж после успешного прохождения всех тестов определённого уровня
Допускается что критерии правил заданы заранее, например на уровне атрибутов модели
Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей

2021-11-19 16:18 UTC, VidgarVii requested changes

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +    class << self
очень плохая идея все методы складировать как методы класса. 
Данный класс больше похож на обычный контейнер каких-то методов. Хорошо что они вроде бы как выполняют одну задачу
Соблюдай соглашение ООП. 
Нужен объект с конструктором, который принимает данные и выполняет поставленную цель.

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        test_passage.user.issued_rewards.build(reward: reward).save
а нет. ошибся. Не одну задачу(

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        RewardIssue.by_category?(test_passage)
методы предикаты могут возвращать только 2 значения либо true либо false. И как правило их используют ради постановки условий для дальнейшего действия.

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        RewardIssue.first_try?(test_passage)
А если современен будет 50 разных правил. То будет 50 вызовов методов? И зачем 3 раза дублировать названия правил? (пока 3 насчитал) 
Код должен быть маштабируем

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        test_passage.user.issued_rewards.build(reward: reward).save
по названию метода вроде тут должна быть какая-то проверка. Но еще и происходит страшный сайд эффект создания issued_rewards

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +  class RewardIssue
IssuedReward RewardIssue как не запутаться?) И кто за что должен отвечать

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +                                     .uniq
так можно просто обратиться к юзеру и получить у него все пройденные тесты. А дальше фильтрануть по уровню.
Используй методы ассоциаций

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        return if completed_tests_by_level.count != tests_by_level.count
вообще весь код с 24 по 32 строчки можно уложить в 1 sql запрос  (но пока не обязательно)

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        return if reward.nil?
не совсем понимаю зачем эти проверки. Для того что бы просто убедиться что они есть в бд? Так не проще было начать с итерации существующих Reward ?

2021-11-19 16:18 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +        return if reward.nil?
а как понять какой уровень надо проверять? 1 или 5?

2021-11-19 16:18 UTC, VidgarVii commented on app/controllers/admin/rewards_controller.rb
> +    params.require(:reward).permit(:name, :image_url, :rule_type, :rule_value)
ага! я нашёл упоминание rule_value))) Жаль дальнейший код не знает о нём =(

2021-11-23 21:29 UTC, Kagayakashi commented on app/services/reward_service/reward_issue.rb
> +  class RewardIssue
IssedReward выданная награда, а RewardIssue сам процесс выдачи :)

2021-11-23 21:33 UTC, Kagayakashi commented on app/services/reward_service/reward_issue.rb
> +        return if reward.nil?
Я сделал попроще. Уровень задается пройденным тестом.

Т.е. пройден тест 2 уровня. Проверяется, пройдены ли на текущий момент все тесты 2 уровня и если да, выдать награду.

Или всё же требуется сделать параметр для правила? Я от него избавлялся)

2021-12-10 07:36 UTC, VidgarVii requested changes

2021-12-10 07:36 UTC, VidgarVii commented on app/controllers/admin/rewards_controller.rb
> +    params.require(:reward).permit(:name, :image_url, :rule_type, :first_try, :by_level, :by_category)
выглядит так то кол-во полей зависит от кол-ва типов правил. Правил может быть тысячи. И только увеличиваться. Этот момент надо учитывать. Для работы достатоно выделить 2 поля для правила. rule_type и rule_value

2021-12-10 07:36 UTC, VidgarVii commented on app/controllers/issued_rewards_controller.rb
> +    @issued_rewards = current_user.rewards
можно всё показать на 1 странице. Список всех возможных наград и  сверху уже заработанные

2021-12-10 07:36 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      @test_passage.completed = true if @test_passage.test_result_good?
1 не совсем понятно чем finished отличается от completed
2 зачем это вообще надо? чем плох метод finished?
3 А не лучше это делать в модели?

2021-12-10 07:36 UTC, VidgarVii commented on app/models/reward.rb
> +  enum rules: [:first_try, :by_level, :by_category]
всегда фризь коллекции, чтобы нельзя было их изменить в рантайме

2021-12-10 07:36 UTC, VidgarVii commented on app/models/reward.rb
> +  enum rules: [:first_try, :by_level, :by_category]
https://github.com/rubocop/rails-style-guide#enums

2021-12-10 07:36 UTC, VidgarVii commented on app/services/reward_service/reward_issue.rb
> +      Reward.all.each do |reward|
https://github.com/rubocop/rails-style-guide#find-each

2021-12-26 18:34 UTC, merged