Scope & Validation (6)
Kagayakashi/learn_rails pull request #5
Opened 2020-11-01 22:42 UTC by Kagayakashi

2020-11-04 17:19 UTC, max-underthesun commented on app/models/answer.rb
> +  }
не совсем ясна концепция этого скоупа
он несколко не соответсвуует ТЗ
там ничего не упоминается про принадлежность ответов каким-то вопросам
даже если писать с привязкой к вопросам, что думаю лишнее, мне не ясно зачем джойнить таблицу вопросов

2020-11-04 17:19 UTC, max-underthesun commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2020-11-04 17:19 UTC, max-underthesun commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
>ТЗ: "У одного Вопроса может быть от 1-го до 4-х ответов."

валидация в модели `Question` не будет препятствовать созданию новых объектов модели `Answer` в количестве больше 4, потому что она не будет вызываться при добавлении новых ответов к вопросу
валидации в классе `Question` вызываются при создании или изменении объектов класса `Question`
при создании объектов класса `Answer` валидации в классе `Question` не вызываются

ты проверял работу этой валидации?
попробуй в консоли, должно получиться создать больше 4-х ответов на один вопрос

2020-11-04 17:19 UTC, max-underthesun commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
второй момент (тесно связанный с первым)
валидацию на минимальное количество лучше не делать, потому что валидация на минимальное количество после ее правильной реализации может заметно усложнить наше учебное приложение, т.к. вопрос нужно будет создавать одновременно с ответом хотя бы одним

2020-11-04 17:19 UTC, max-underthesun commented on app/models/test.rb
> +  default_scope { order(created_at: :desc) }
хотя по ТЗ и надо добавить `default_scope` в класс `Category`, но вообще использовать `default_scope` крайне не рекомендуется
если интересно - погугли что нибудь на тему 'rails default scope is evil'

2020-11-04 17:19 UTC, max-underthesun commented on app/models/user.rb
> +  validates :email, presence: true
это лучше в одну строчку конечно же... типа `validates :some, :one_more, presence: true` посмотри доки

2020-11-05 17:02 UTC, VidgarVii requested changes

2020-11-07 19:08 UTC, merged